-- EXECUTE ESTAS LINHAS NO SQL EDITOR DO SUPABASE PARA LIBERAR O ACESSO AOS DADOS
ALTER TABLE admins DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_stores DISABLE ROW LEVEL SECURITY;
ALTER TABLE lojas DISABLE ROW LEVEL SECURITY;
ALTER TABLE auditorias DISABLE ROW LEVEL SECURITY;
ALTER TABLE itens_auditoria DISABLE ROW LEVEL SECURITY;
